site_name: DevBlog
site_url: https://mydomain.org/blog/
theme:
  palette:
    scheme: slate
    primary: black
    accent: indigo
  name: material
  features:
    - content.code.copy
    - navigation.indexes
plugins:
  - blog:
      archive: false
nav:
  - Home: index.md
  - Blog: 
    - blog/index.md
extra:
  generator: false # Do not generate ad in footer 
markdown_extensions: # Syntax Highlighting
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list # Emojis
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg